# Generated by Django 4.1.1 on 2024-01-26 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.frame'),
        ),
    ]
