# Generated by Django 4.1.1 on 2024-01-26 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bike_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.frame'),
        ),
    ]
